language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run pretest
  - yarn run test
deploy:
  - provider: npm
    skip_cleanup: true
    email: $npm_email
    api_key: $npm_token
    on:
      tags: true
keep-history: true